services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        buildno: 1
    container_name: frontend
    ports:
      - 3000:3000
    networks:
      task:

  workshop-api:
    build:
      context: ./workshop
      dockerfile: Dockerfile
      args:
        buildno: 1
    container_name: workshop-api
    ports:
      - 8080:8080
    networks:
      task:

  nginx:
    image: nginx:1.25.3
    ports:
      - 80:80
    depends_on:
      - frontend
      - workshop-api
    networks:
      task:
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  manchester-tire-workshop:
    image: surmus/manchester-tire-workshop:2.0.1
    networks:
      task:

  london-tire-workshop:
    image: surmus/london-tire-workshop:2.0.1
    networks:
      task:

networks:
  task:
    driver: bridge